# Generated by Django 4.2.13 on 2024-06-15 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_preference', models.CharField(choices=[('email', 'Email'), ('discord', 'Discord')], default='email', max_length=7)),
                ('discord_webhook_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar'), ('INR', 'Indian Rupees'), ('CAD', 'Canadian Dollar')], default=('USD', 'United States Dollar'), max_length=10)),
                ('change_per', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=12)),
                ('domain', models.CharField(choices=[('COM', 'United States (com)'), ('UK', 'United Kingdom (uk)'), ('CA', 'Canada (ca)'), ('AU', 'Australia (au)'), ('DE', 'Germany (gr)')], default='COM', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.URLField(default=None)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
