# Generated by Django 5.0.6 on 2024-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdb',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
