# Generated by Django 4.2.13 on 2024-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdb',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsdb',
            name='last_checked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
