# Generated by Django 4.2.13 on 2024-06-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_productsdb_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdb',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
