# Generated by Django 4.2.13 on 2024-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_productsdb_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
