# Generated by Django 4.2.13 on 2024-06-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_usersettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdb',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.currencyrate'),
        ),
    ]
