# Generated by Django 4.2.13 on 2024-06-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_productsdb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='domain_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
