# Generated by Django 4.2.13 on 2024-06-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_currencyrate_domain_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdb',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
