# Generated by Django 4.2.13 on 2024-06-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
