# Generated by Django 4.2.13 on 2024-06-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_productsdb_last_checked_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsdb',
            name='last_checked_price_currency',
        ),
        migrations.RemoveField(
            model_name='productsdb',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='productsdb',
            name='last_checked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsdb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
