# Generated by Django 4.2.13 on 2024-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_productsdb_last_checked_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdb',
            name='is_stock',
            field=models.BooleanField(default=False),
        ),
    ]
