# Generated by Django 4.2.13 on 2024-06-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_productsdb_is_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsdb',
            old_name='is_stock',
            new_name='in_stock',
        ),
    ]
