# Generated by Django 4.2.13 on 2024-07-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_is_stock_productsdb_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='updated_at',
            new_name='timestamp',
        ),
    ]
